[package]
name = "myrt"
version = "0.1.0"
authors = ["Oliver Hunt <github@nerget.com>"]

[dependencies]
image = "*"
genmesh = "*"
itertools = "*"
rand = "*"
packed_simd = "*"
rayon-core = "*"
obj = { version = "*", features = ["genmesh"]}

[dependencies.clap]
features = ["yaml"]
git = "https://github.com/clap-rs/clap.git"
branch = "master"

[dependencies.faster]
git = "https://github.com/AdamNiederer/faster.git"
branch = "master"

[profile.release]
debug = true
