[package]
name = "myrt"
version = "0.1.0"
authors = ["Oliver Hunt <oliver@apple.com>"]

[dependencies]
image = "*"
genmesh = "*"
itertools = "*"
rand = "*"
stdsimd = "*"
obj = { version = "*", features = ["genmesh"]}

[dependencies.clap]
features = ["yaml"]
git = "https://github.com/clap-rs/clap.git"
branch = "master"

[profile.release]
debug = true
